"""empty message

Revision ID: 2d4355c91ba2
Revises: 5866992716c4
Create Date: 2016-11-25 15:40:36.468928

"""

# revision identifiers, used by Alembic.
revision = '2d4355c91ba2'
down_revision = '5866992716c4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_emails', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_deleted')
    op.drop_column('user_emails', 'is_deleted')
    ### end Alembic commands ###
