"""empty message

Revision ID: 5866992716c4
Revises: ad46ff5cbff1
Create Date: 2016-11-22 23:24:45.997930

"""

# revision identifiers, used by Alembic.
revision = '5866992716c4'
down_revision = 'ad46ff5cbff1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_emails',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('user_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['users.user_name'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_constraint('users_email_key', 'users', type_='unique')
    op.drop_column('users', 'email')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.TEXT(), autoincrement=False, nullable=False))
    op.create_unique_constraint('users_email_key', 'users', ['email'])
    op.drop_table('user_emails')
    ### end Alembic commands ###
